describe('Register Testing', () => {

    before(() => {
        cy.exec('php artisan user:delete user@gmail.com', { failOnNonZeroExit: false });
    });

    it('TC-REG-01 Registrasi berhasil dengan data valid', () => {
        cy.visit('/register')
        cy.get('input[name="name"]').should('be.visible').type("user")
        cy.wait(300)
        cy.get('input[name="email"]').should('be.visible').type("user@gmail.com")
        cy.wait(300)
        cy.get('input[name="password"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('input[name="password_confirmation"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('button[type="submit"]').should('be.visible').click()
        cy.wait(500)
    })

    it('TC-REG-02 Menolak email bukan domain gmail', () => {
        cy.visit('/register')
        cy.get('input[name="name"]').should('be.visible').type("user")
        cy.wait(300)
        cy.get('input[name="email"]').should('be.visible').type("user@yahoo.com")
        cy.wait(300)
        cy.get('input[name="password"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('input[name="password_confirmation"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('button[type="submit"]').should('be.visible').click()
        cy.wait(500)
        cy.contains("Email harus menggunakan domain @gmail.com").should('be.visible')
    })

    it('TC-REG-03 Menolak email yang sudah terdaftar', () => {
        cy.visit('/register')
        cy.get('input[name="name"]').should('be.visible').type("user")
        cy.wait(300)
        cy.get('input[name="email"]').should('be.visible').type("user@gmail.com")
        cy.wait(300)
        cy.get('input[name="password"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('input[name="password_confirmation"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('button[type="submit"]').should('be.visible').click()
        cy.wait(500)
        cy.contains("The email has already been taken").should('be.visible')
    })

    it('TC-REG-04 Menolak password kurang dari 8 karakter', () => {
        cy.visit('/register')
        cy.get('input[name="name"]').should('be.visible').type("testuser")
        cy.wait(300)
        cy.get('input[name="email"]').should('be.visible').type("testuser@gmail.com")
        cy.wait(300)
        cy.get('input[name="password"]').should('be.visible').type("Usr12#")
        cy.wait(300)
        cy.get('input[name="password_confirmation"]').should('be.visible').type("Usr12#")
        cy.wait(300)
        cy.get('button[type="submit"]').should('be.visible').click()
        cy.wait(500)
        cy.contains("The password field must be at least 8 characters").should('be.visible')
    })

    it('TC-REG-05 Menolak password tanpa huruf besar/angka/simbol', () => {
        cy.visit('/register')
        cy.get('input[name="name"]').should('be.visible').type("testuser")
        cy.wait(300)
        cy.get('input[name="email"]').should('be.visible').type("testuser@gmail.com")
        cy.wait(300)
        cy.get('input[name="password"]').should('be.visible').type("user1234")
        cy.wait(300)
        cy.get('input[name="password_confirmation"]').should('be.visible').type("user1234")
        cy.wait(300)
        cy.get('button[type="submit"]').should('be.visible').click()
        cy.wait(500)
        cy.contains("Password harus mengandung huruf besar, angka, simbol, serta minimal 8 karakter").should('be.visible')
    })

    it('TC-REG-06 Menolak konfirmasi password tidak cocok', () => {
        cy.visit('/register')
        cy.get('input[name="name"]').should('be.visible').type("testuser")
        cy.wait(300)
        cy.get('input[name="email"]').should('be.visible').type("testuser@gmail.com")
        cy.wait(300)
        cy.get('input[name="password"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('input[name="password_confirmation"]').should('be.visible').type("User#12345")
        cy.wait(300)
        cy.get('button[type="submit"]').should('be.visible').click()
        cy.wait(500)
        cy.contains("The password confirmation does not match").should('be.visible')
    })

    it('TC-REG-07 Menampilkan pesan error spesifik (multiple errors)', () => {
        cy.visit('/register')
        cy.get('input[name="name"]').should('be.visible').type("testuser")
        cy.wait(300)
        cy.get('input[name="email"]').should('be.visible').type("testuser@yahoo.com")
        cy.wait(300)
        cy.get('input[name="password"]').should('be.visible').type("user1234")
        cy.wait(300)
        cy.get('input[name="password_confirmation"]').should('be.visible').type("user12345")
        cy.wait(300)
        cy.get('button[type="submit"]').should('be.visible').click()
        cy.wait(500)
        cy.contains("Email harus menggunakan domain @gmail.com").should('be.visible')
        cy.contains("The password confirmation does not match").should('be.visible')
    })

    it('TC-REG-08 Menolak nama > 100 karakter', () => {
        cy.visit('/register')
        cy.get('input[name="name"]').should('be.visible').type("a".repeat(101))
        cy.wait(300)
        cy.get('input[name="email"]').should('be.visible').type("user255@gmail.com")
        cy.wait(300)
        cy.get('input[name="password"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('input[name="password_confirmation"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('button[type="submit"]').should('be.visible').click()
        cy.wait(500)
        cy.contains("The name field must not be greater than 100 characters").should('be.visible')
    })

    it('TC-REG-09 Menolak email > 100 karakter', () => {
        cy.visit('/register')
        cy.get('input[name="name"]').should('be.visible').type("user")
        cy.wait(300)
        cy.get('input[name="email"]').should('be.visible').type("a".repeat(101) + "@gmail.com")
        cy.wait(300)
        cy.get('input[name="password"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('input[name="password_confirmation"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('button[type="submit"]').should('be.visible').click()
        cy.wait(500)
        cy.contains("The email field must not be greater than 100 characters.").should('be.visible')
    })

    it('TC-REG-10 Menolak field nama kosong', () => {
        cy.visit('/register')
        cy.get('input[name="name"]').should('be.visible').clear()
        cy.wait(300)
        cy.get('input[name="email"]').should('be.visible').type("user@gmail.com")
        cy.wait(300)
        cy.get('input[name="password"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('input[name="password_confirmation"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('button[type="submit"]').should('be.visible').click()
        cy.wait(500)
        cy.contains("The name field is required").should('be.visible')
    })

    it('TC-REG-11 Menolak field email kosong', () => {
        cy.visit('/register')
        cy.get('input[name="name"]').should('be.visible').type("user")
        cy.wait(300)
        cy.get('input[name="email"]').should('be.visible').clear()
        cy.wait(300)
        cy.get('input[name="password"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('input[name="password_confirmation"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('button[type="submit"]').should('be.visible').click()
        cy.wait(500)
        cy.contains("The email field is required").should('be.visible')
    })

    it('TC-REG-12 Menolak password kosong', () => {
        cy.visit('/register')
        cy.get('input[name="name"]').should('be.visible').type("user")
        cy.wait(300)
        cy.get('input[name="email"]').should('be.visible').type("user@gmail.com")
        cy.wait(300)
        cy.get('input[name="password"]').should('be.visible').clear()
        cy.wait(300)
        cy.get('input[name="password_confirmation"]').should('be.visible').clear()
        cy.wait(300)
        cy.get('button[type="submit"]').should('be.visible').click()
        cy.wait(500)
        cy.contains("The password field is required").should('be.visible')
    })

    it('TC-REG-13 Menolak konfirmasi password kosong', () => {
        cy.visit('/register')
        cy.get('input[name="name"]').should('be.visible').type("user")
        cy.wait(300)
        cy.get('input[name="email"]').should('be.visible').type("user@gmail.com")
        cy.wait(300)
        cy.get('input[name="password"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('input[name="password_confirmation"]').should('be.visible').clear()
        cy.wait(300)
        cy.get('button[type="submit"]').should('be.visible').click()
        cy.wait(500)
        cy.contains("The password confirmation does not match").should('be.visible')
    })

    it('TC-REG-14 Menolak format email tidak valid', () => {
        cy.visit('/register')
        cy.get('input[name="name"]').should('be.visible').type("user")
        cy.wait(300)
        cy.get('input[name="email"]').should('be.visible').type("usergmail.com")
        cy.wait(300)
        cy.get('input[name="password"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('input[name="password_confirmation"]').should('be.visible').type("User#1234")
        cy.wait(300)
        cy.get('button[type="submit"]').should('be.visible').click()
        cy.wait(500)
        cy.contains("The email field must be a valid email address").should('be.visible')
    })
})
